### ISSUE TITLE
Error when running crawling example

### ISSUE THREAD

**Issue by BitnomadLive** [mariussteffens/pmforce#1]
Hi,

I just tried to run:
`node crawly.js --mode test --headless --module pm --url 'http://127.0.0.1:8000/conditionalOr.html'`
and I ran into the follwing error:
```
Tue May 11 2021 17:54:51 [Crawly] [Info] Creating instance of Dynamic Module pm
Tue May 11 2021 17:54:52 [Crawly] [Error] { [Error: ENOENT: no such file or directory, open './external/pm/dist/bundle.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './external/pm/dist/bundle.js' }
```
so I run webpack to try and generate the missing bundle.js, but I got the follwing error:
```
webpack -d
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN saveError ENOENT: no such file or directory, open '/crawly/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/crawly/package.json'
npm WARN crawly No description
npm WARN crawly No repository field.
npm WARN crawly No README data
npm WARN crawly No license field.

+ webpack-cli@4.7.0
updated 1 package and audited 301 packages in 2.605s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at runCli (/usr/local/lib/node_modules/webpack/bin/webpack.js:50:26)
    at runCommand.then (/usr/local/lib/node_modules/webpack/bin/webpack.js:139:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```
It seems like files are missing. Could you maybe check wether you forgot to upload the package.json file ?

**Comment by mariussteffens** [comment]
Hey there,

thanks for reaching out! 

The pre-bundled ```./external/pm/dist/bundle.js```  was missing from the repo due to a more restrictive ```.gitignore```. 
I have taken the opportunity to pin the versions of webpack for which the setup works (they changed some things in the latest version).

You should now be able to use the pre-bundled version, or inside the docker execute ```webpack -d``` in the ```external/pm``` folder to update the bundle if you happen to make some changes to the analysis pipeline.

Let me know if this works for you!
Cheers,
Marius

**Comment by BitnomadLive** [comment]
Thanks for the fast reply.
When running docker build & docker-compose up I got the following errors (shortened for better readability):
```
Step 9/11 : RUN sh install.sh
 ---> Running in 4f35991536c7
rm: cannot remove 'package-lock.json': No such file or directory
```
Seems like there is something wrong with the install.sh file but it finished building and I successfully run the test module.
In the same step there were some additional warnings:
```
Chromium (869685) downloaded to /crawly/node_modules/puppeteer/.local-chromium/linux-869685
npm WARN saveError ENOENT: no such file or directory, open '/crawly/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/crawly/package.json'
npm WARN crawly No description
npm WARN crawly No repository field.
npm WARN crawly No README data
npm WARN crawly No license field.

[...]
added 85 packages from 87 contributors and audited 85 packages in 34.498s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/usr/local/bin/webpack-cli -> /usr/local/lib/node_modules/webpack-cli/bin/cli.js
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack/node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
But like I already mentioned it finished building and worked fine.

When running local_test.sh I ran into the following errors:
```
root@404de31fe974:/crawly# sh local_test.sh
Wed May 12 2021 18:47:58 [Crawly] [Info] Loading Modules...
Wed May 12 2021 18:47:58 [Crawly] [Info] Loading Dynamic Module pm
Wed May 12 2021 18:47:58 [Crawly] [Info] Finished loading Modules!
Wed May 12 2021 18:47:58 [Crawly] [Info] you are making use of a dangerous functionality, with great power comes great responsibility...
Wed May 12 2021 18:47:58 [Crawly] [Info] Are you certain that you want to drop the following tables:
Wed May 12 2021 18:47:58 [Crawly] [Info] Host: db
Wed May 12 2021 18:47:58 [Crawly] [Info] DB: crawly
Wed May 12 2021 18:47:58 [Crawly] [Info] Modules: [ 'pm' ]
Wed May 12 2021 18:47:58 [Crawly] [Info] Be warned that even if you did not supply a module, this functionality will clean the core tables such as urls, frames, and jobs.
Are you really sure? y/n
y
(node:286) DeprecationWarning: ArgumentParser(): following options are renamed: 'addHelp' -> 'add_help'
(node:286) DeprecationWarning: The "version" argument to ArgumentParser is deprecated. Please use add_argument(..., { action: 'version', version: 'N', ... }) instead.
(node:286) DeprecationWarning: _ActionsContainer.addArgument() is renamed to _ActionsContainer.add_argument()
(node:286) DeprecationWarning: {action: "storeTrue"} is renamed to {action: "store_true"}
(node:286) DeprecationWarning: add_argument(): following options are renamed: 'defaultValue' -> 'default'
(node:286) DeprecationWarning: ArgumentParser.parseArgs() is renamed to ArgumentParser.parse_args()
Wed May 12 2021 18:48:14 [Crawly] [Info] Deleting Databases...
Wed May 12 2021 18:48:14 [Crawly] [Info] DROP TABLE job
Wed May 12 2021 18:48:14 [Crawly] [Error] { error: table "job" does not exist
    at Parser.parseErrorMessage (/crawly/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/crawly/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/crawly/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/crawly/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 98,
  name: 'error',
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '1213',
  routine: 'DropErrorMsgNonExistent' }
Wed May 12 2021 18:48:14 [Crawly] [Info] DROP TABLE frames
Wed May 12 2021 18:48:14 [Crawly] [Error] { error: table "frames" does not exist
    at Parser.parseErrorMessage (/crawly/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/crawly/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/crawly/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/crawly/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 101,
  name: 'error',
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '1213',
  routine: 'DropErrorMsgNonExistent' }
[..errors for every table there is I guess ...]
```

When running  ./spawn.sh 1 1 --mode run --job_id 1 --module pm --headless
afterwards and taking a look into the generated log file.
There was this following error:
```

Wed May 12 2021 18:49:23 [Crawly] [Info] waiting for results to be entered in DB
Wed May 12 2021 18:49:23 [Crawly] [Info] waiting for filedisk writes
Wed May 12 2021 18:49:23 [Crawly] [Error] { [Error: ENOENT: no such file or directory, open '/tmp/handlers//41/41e764f40b15cdda3714d7c69408fceb']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/handlers//41/41e764f40b15cdda3714d7c69408fceb' }
Wed May 12 2021 18:49:23 [Crawly] [Benchmark] execute chain of pm finished in 5 ms
Wed May 12 2021 18:49:23 [Crawly] [Info] Finished with modules...
Wed May 12 2021 18:49:23 [Crawly] [Info] Successfully crawled:  7
Wed May 12 2021 18:49:23 [Crawly] [Benchmark] Crawling of site http://127.0.0.1:8000/indexOfOriginCheck.html finished in 10471 ms
Wed May 12 2021 18:49:23 [Crawly] [Info] Finished Job http://127.0.0.1:8000/indexOfOriginCheck.html
Wed May 12 2021 18:49:23 [Crawly] [Info] Tearing down Chrome...
Wed May 12 2021 18:49:23 [Crawly] [Info] Killing browser with pid 426
clearing profile /tmp/node-crawler1/
node start.js --crawler_id 1  --user_data_dir /tmp/node-crawler1/ --mode run --job_id 1 --module pm --headless;

```
not sure why this one happens though (probably because there is an extra / in the path?).  In between, there are normal logs with no errors at all, so this seems to be alright.
Just another question:

When running  ./spawn.sh 1 1 --mode run --job_id 1 --module pm --headless
Am I supposed to give the range of how many URLs there are? (with 16 URLs:  ./spawn.sh 1 16)?

Kind regards

**Comment by mariussteffens** [comment]
The first error that you pasted stems from executing the project both in the container and on my native machine. 
In that case, the node_modules and package-lock.json that might be present due to running ```install.sh``` on the host machine might interfere with the installation process in the container. That is why they are removed if present (leading to an error if they are not). However, this should not break anything.

As for the second error, the ```local_test.sh``` removes all tables in the DB, and then creates the necessary tables again and fills them with the test urls. If the tables are not present these errors are raised. Regardless, even if these errors occur everything will be initialized correctly. Although coming from a fresh container, these issues should not occur(tm).

As for the last error, again not breaking anything, yet I have changed the location to which the encountered postMessage handlers should be saved to. This will now work correctly in the container and postMessage handlers will be saved to ```/handlers/```.

```spawn.sh``` takes care of running a specific number of crawlers all with their own ```--crawler_id```. 
Running ```./spawn.sh 1 16 [...]``` would in turn start 16 crawlers. Every crawlers runs for as long as it can find more URLs to crawl in the DB.
